<h1>Practice for Numpy Lib</h1>

In [1]:
import numpy as np

In [39]:
a = np.array([1,1,1,1,1])
b = np.array(a/2)
np.ones(5)

array([1., 1., 1., 1., 1.])

In [40]:
np.sum(a+b)

7.5

In [35]:
np.arange(5,10,2)

array([5, 7, 9])

In [36]:
np.linspace(0,20,num=10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [37]:
np.empty(3)

array([1.30487447e-311, 0.00000000e+000, 6.47591605e-319])

In [41]:
c = np.array([2,34,52,326,46,345,23,235,6,57,683,54,52,342,4,235,47,3])
np.sort(c)

array([  2,   3,   4,   6,  23,  34,  46,  47,  52,  52,  54,  57, 235,
       235, 326, 342, 345, 683])